version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: py_micro_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - py_micro_net

  redis:
    image: redis:7-alpine
    container_name: py_micro_redis
    networks:
      - py_micro_net

  backend:
    build:
      context: ./backend
    container_name: py_micro_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - py_micro_net

  frontend:
    build:
      context: ./frontend
    container_name: py_micro_frontend
    depends_on:
      - backend
      - redis
    ports:
      - "5001:5000"
    networks:
      - py_micro_net

  nginx:
    image: nginx:stable
    container_name: py_micro_nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - py_micro_net

volumes:
  db_data:

networks:
  py_micro_net:
    driver: bridge
